---
pre_onboard_enabled: []
runtime_parameters:
  - name: HOST_NAME
    type: metadata
    metadataProvider:
      environment: aws
      type: compute
      field: hostname
  - name: REGION
    type: url
    value: http://169.254.169.254/latest/dynamic/instance-identity/document
    query: region
extension_packages:
  install_operations:
  - extensionType: do
    extensionVersion: 1.16.0
    extensionHash: 536eccb9dbf40aeabd31e64da8c5354b57d893286ddc6c075ecc9273fcca10a1
  - extensionType: as3
    extensionVersion: 3.20.0
    extensionHash: ba2db6e1c57d2ce6f0ca20876c820555ffc38dd0a714952b4266c4daf959d987
  - extensionType: ts
    extensionVersion: 1.12.0
    extensionHash: d52ad1ca23df1d9c81a9e3641fc25b593dd0c0a17cc3a90316067ae78e41a990
extension_services:
  service_operations:
  - extensionType: do
    type: inline
    value:
      Common:
        class: Tenant
        dbvars:
          class: DbVariables
          provision.extramb: 500
          restjavad.useextramb: true
          ui.advisory.enabled: true
          ui.advisory.color: green
          ui.advisory.text: "Provisioned via Runtime Init and DO"
        myDns:
          class: DNS
          nameServers:
          - 8.8.8.8
        myNtp:
          class: NTP
          servers:
          - 0.pool.ntp.org
          timezone: UTC
        myProvisioning:
          class: Provision
          ltm: nominal
          asm: nominal
        mySystem:
          autoPhonehome: true
          class: System
          hostname: '{{{ HOST_NAME }}}'
      async: true
      class: Device
      label: myBIG-IPdeclarationfordeclarativeonboarding
      schemaVersion: 1.0.0
  - extensionType: as3
    type: inline
    value:
      remark: ASM_VS1
      schemaVersion: 3.0.0
      label: ASM_VS1
      class: ADC
      Tenant_1:
        class: Tenant
        Shared:
          class: Application
          template: shared
          shared_pool:
            class: Pool
            remark: Service 1 shared pool
            monitors:
            - http
            members:
            - servicePort: 80
              addressDiscovery: aws
              region: '{{{ REGION }}}'
              updateInterval: 20
              tagKey: aws:cloudformation:logical-id
              tagValue: appAutoscaleGroup
              addressRealm: private
        HTTP_Service:
          template: http
          class: Application
          serviceMain:
            class: Service_HTTP
            virtualAddresses:
            - 0.0.0.0
            snat: auto
            policyWAF:
              use: WAFPolicy
            pool: "/Tenant_1/Shared/shared_pool"
          WAFPolicy:
            ignoreChanges: true
            url: https://raw.githubusercontent.com/f5-applebaum/deployments-v2/0.0.2/dev/aws/bigip-configurations/owasp-auto-tune-v1.1.xml
            class: WAF_Policy
        HTTPS_Service:
          template: https
          class: Application
          serviceMain:
            virtualAddresses:
            - 0.0.0.0
            snat: auto
            policyWAF:
              use: WAFPolicy
            pool: "/Tenant_1/Shared/shared_pool"
            serverTLS:
              bigip: "/Common/clientssl"
            redirect80: false
            class: Service_HTTPS
          WAFPolicy:
            ignoreChanges: true
            url: https://raw.githubusercontent.com/f5-applebaum/deployments-v2/0.0.2/dev/aws/bigip-configurations/owasp-auto-tune-v1.1.xml
            class: WAF_Policy
  - extensionType: ts
    type: inline
    value:
      class: Telemetry
      My_System:
        class: Telemetry_System
        systemPoller:
          interval: 60
      My_Listener:
        class: Telemetry_Listener
        port: 6514
      My_Consumer:
        class: Telemetry_Consumer
        type: AWS_S3
        region: '{{{ REGION }}}'
        bucket: demo
        username: XXXXX
        passphrase:
          cipherText: XXXXXXXXX
post_onboard_enabled: []
